### ISSUE TITLE
rename the standalone tool name to `go-coverage-tool` later.

### ISSUE THREAD

**Issue by ccoVeille** [xhd2015/xgo#102]
Created from this discussion

_Originally posted by @xhd2015 in https://github.com/xhd2015/xgo/issues/98#issuecomment-2101988746_

**Comment by xhd2015** [comment]
Addressed in https://github.com/xhd2015/xgo/pull/104,  not tagged currently, can be installed via:
```sh
go install gitub.com/xhd2015/xgo/cmd/go-tool-coverage@master
```
