### ISSUE TITLE
xgo failed to run tests on Windows

### ISSUE THREAD

**Issue by Zxilly** [xhd2015/xgo#103]
I created a test with xgo on https://github.com/Zxilly/go-size-analyzer/blob/master/internal/printer/json_xgo_test.go. But when I run the test with

```bash
xgo test -v -race -covermode=atomic -cover ./... -tags xgo,embed
```

It tolds me

```log
open C:\Users\zxilly\.xgo\go-instrument\go1.22.3_C_Us_12_go_pk_mo_go_to_7f0da9bd\go1.22.3\src\runtime\proc.go: The system cannot find the path specified.
```

The dir structure of `C:\Users\zxilly\.xgo\go-instrument\go1.22.3_C_Us_12_go_pk_mo_go_to_7f0da9bd\` is 

```log
    Directory: C:\Users\zxilly\.xgo\go-instrument\go1.22.3_C_Us_12_go_pk_mo_go_to_7f0da9bd

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2024/5/10    11:36                pkgdata
```

nothing in the pkgdata directory.

I'm running go 1.22.3 and xgo 1.0.31, build with go install.

**Comment by Zxilly** [comment]
The project using go toolchain, is this leading to the error?

**Comment by xhd2015** [comment]
Thanks for raising the issue, I will take a deep look later.
This project requires `$GOROOT/src` exists because it needs to instrument the go runtime and compiler. Can you confirm if your `GOROOT` contains a `src` directory?

Besides can you try to run this within WSL to see if it works?

Thanks.

**Comment by Zxilly** [comment]
Here's `go env`
```
go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\zxilly\AppData\Local\go-build
set GOENV=C:\Users\zxilly\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\zxilly\go\pkg\mod
set GONOPROXY=1
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\zxilly\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:/Users/zxilly/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.windows-amd64
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Users\zxilly\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.22.3.windows-amd64\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\Project\CS_Project\gsv\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\zxilly\AppData\Local\Temp\go-build2969563362=/tmp/go-build -gno-record-gcc-switches
```

**Comment by xhd2015** [comment]
Seems like go-toolchain related. I'll try later

**Comment by Zxilly** [comment]
On linux it works but mock failed.

```log
panic: failed to setup mock for: encoding/json.Marshal [recovered]
        panic: failed to setup mock for: encoding/json.Marshal
```

But I guess it's a limitation of xgo itself that the build was successful

**Comment by xhd2015** [comment]
> On linux it works but mock failed.
> 
> ```
> panic: failed to setup mock for: encoding/json.Marshal [recovered]
>         panic: failed to setup mock for: encoding/json.Marshal
> ```
> 
> But I guess it's a limitation of xgo itself that the build was successful

Yes because only a small part of stdlib are injected. See https://github.com/xhd2015/xgo/blob/master/runtime/mock/stdlib.md.
But if that is necessary, I can add support for them.

**Comment by xhd2015** [comment]
The failure caused this issue on windows has been fixed in https://github.com/xhd2015/xgo/pull/109

**Comment by Zxilly** [comment]
I still think hook stdlib is quite important, because in other cases we always have the opportunity to get around the need for hooks by writing test-friendly code, but some modifications to the standard library prevent the code from compiling on other machines, which makes a monkey patch inevitable.

**Comment by xhd2015** [comment]
> I still think hook stdlib is quite important, because in other cases we always have the opportunity to get around the need for hooks by writing test-friendly code, but modifications to the standard library prevent the code from compiling on other machines, which makes a monkey patch inevitable.

@Zxilly OK I got your point. I also feel it would be more feasible if xgo allows user to specify what stdlib funcs they want to mock. I will take a look on this more deeply.

By the way, do you have any case that would require mocking specific stdlib functions? You can post an example here or raise another issue so that we have a better understanding of the problem.

Thanks.

**Comment by Zxilly** [comment]
```go
func download() (string, error) {
	slog.Info("Downloading template")
	resp, err := http.Get(BaseURL)
	if err != nil {
		return "", err
	}
	defer func(body io.ReadCloser) {
		_ = body.Close()
	}(resp.Body)

	// check status code
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("failed to download template: %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(body), nil
}
```

```go
func getCacheFilePath() (string, error) {
	dir, err := os.UserCacheDir()
	if err != nil {
		return "", err
	}

	cacheDir := filepath.Join(dir, "go-size-analyzer")

	err = os.MkdirAll(cacheDir, 0755)
	if err != nil {
		return "", err
	}

	file := filepath.Join(cacheDir, fmt.Sprintf("webui-v%s.html", gsa.StaticVersion))

	return file, nil
}
```

In fact, both of these examples can be tested by replacing the corresponding calls with variables, but this amounts to adding runtime complexity for the sake of the test

**Comment by xhd2015** [comment]
@Zxilly This is being resolved in this PR: https://github.com/xhd2015/xgo/pull/117 . Will be available in the next version of xgo at 2024-05-20

**Comment by xhd2015** [comment]
@Zxilly v1.0.36 has been released, see https://github.com/xhd2015/xgo/releases/tag/v1.0.36

**Comment by Zxilly** [comment]
Is that possible to automatic set a build tag for `trap-stdlib`?

**Comment by xhd2015** [comment]
It is possible to automatically add `--trap-stdlib` when `xgo test` is used. But since xgo v1.0.36 is the first release introducing this flag, I think I need to test this flag against some large projects like kubernetes to see if it has any impact.

If all tests go well, I'll make this flag default in the future version.

**Comment by xhd2015** [comment]
> It is possible to automatically add `--trap-stdlib` when `xgo test` is used. But since xgo v1.0.36 is the first release introducing this flag, I think I need to test this flag against some large projects like kubernetes to see if it has any impact.
> 
> If all tests go well, I'll make this flag default in the future version.

Once we fixed the bug in https://github.com/xhd2015/xgo/issues/164, this will be made default.

**Comment by xhd2015** [comment]
@Zxilly `--trap-stdlib` has been made default when running `xgo test`, released  with https://github.com/xhd2015/xgo/releases/tag/v1.0.38.

To install xgo v1.0.38:

```sh
# update xgo
go install github.com/xhd2015/xgo/cmd/xgo@v1.0.38

# update dependency
go get github.com/xhd2015/xgo/runtime@v1.0.38
```

Thanks.
