### ISSUE TITLE
Proposal: use text files to patch runtime and compiler

### ISSUE THREAD

**Issue by mackong** [xhd2015/xgo#147]
Rational: Currently we use string search and replace to edit various runtime and compiler files, which is cumbersome and may easily impact on old versions when support new versions.
Implementation: we can prepare patched files for runtime and compiler of various golang versions，and just file copy for supported version. For unsupported version, we can fallback to current implementation.

**Comment by xhd2015** [comment]
We can this strategy *file replacement*.

And even more, we can be precise on what want to replace: it's function bodies of specific functions we want to replace.
So we can take a step further: only replace functions appear in the patch file. 

This way, we do not need to repeat the unchanged part in both the source file and the patch file.

This can be called *function replacement*.

**Comment by xhd2015** [comment]
Addressed in https://github.com/xhd2015/xgo/issues/203#issuecomment-2241901476
