### ISSUE TITLE
documentation: use Autocorrect for CJK documentation

### ISSUE THREAD

**Issue by ccoVeille** [xhd2015/xgo#149]
This tool is pretty interesting https://github.com/huacnlee/autocorrect

It can be added to GHA via https://github.com/huacnlee/autocorrect-action/

I cannot speak Chinese, but it seems able to provide some good guidance

It reports 139 errors on your repository right now

I'm curious about your thoughts about it.

**Comment by xhd2015** [comment]
I'm open to this but personally I don't think it matters. I prefer English punctuations even in CJK  documentation.

**Comment by ccoVeille** [comment]
OK, so the interest is pretty limited then.
