### ISSUE TITLE
是不是不可以和sonic一起使用

### ISSUE THREAD

**Issue by GaoHaHa-IronMan** [xhd2015/xgo#194]
![image](https://github.com/xhd2015/xgo/assets/34859258/42224cc0-43b4-459d-b77a-c4c7f2de501e)

**Comment by xhd2015** [comment]
感谢反馈，请问下你用的是Go版本是多少？在什么操作系统上？sonic的版本是多少呢？

**Comment by xhd2015** [comment]
我看了下，应该是sonic库的internal/rt这个包只支持amd64导致的：

```sh
git clone --depth=1 https://github.com/bytedance/sonic
cd sonic
mkdir -p ./internal/rt_main
cat > ./internal/rt_main/main.go <<'EOF'
package main

import "github.com/bytedance/sonic/internal/rt"

func main() {
	rt.StartProf()
}
EOF

GOARCH=arm64 go build -o /dev/null ./internal/rt_main
```

Error:
```sh
# github.com/bytedance/sonic/internal/ir_main
main.main: relocation target github.com/bytedance/sonic/internal/rt.StartProf not defined
```

**Comment by GaoHaHa-IronMan** [comment]
> 感谢反馈，请问下你用的是Go版本是多少？在什么操作系统上？sonic的版本是多少呢？

go版本：1.21.6
sonic版本：v1.11.3
操作系统：MacOS13，M2芯片
运行命令： xgo test -v -run TestXXX

**Comment by GaoHaHa-IronMan** [comment]
可以使用 GOARCH=amd64  xgo test -v -run 运行，将架构切换到amd64就能正常运行了，跟在ARM架构上运行gomonkey类似。

**Comment by xhd2015** [comment]
> 可以使用 GOARCH=amd64 xgo test -v -run 运行，将架构切换到amd64就能正常运行了，跟在ARM架构上运行gomonkey类似。

@GaoHaHa-IronMan 你测试的代码有吗？ 这个就是sonic这个包只支持amd64，你用go test也是一样的

**Comment by GaoHaHa-IronMan** [comment]
> > 可以使用 GOARCH=amd64 xgo test -v -run 运行，将架构切换到amd64就能正常运行了，跟在ARM架构上运行gomonkey类似。
> 
> @GaoHaHa-IronMan 这个问题与xgo没有关系，你用go test也会有这个问题。
> 
> 根本原因是sonic这个包只支持amd64。
> 
> 你测试的代码有吗，为什么会引用到github.com/bytedance/sonic/internal/rt这个包呢？

使用go test没有问题，测试代码里没用sonic但是我的业务代码里使用了sonic

**Comment by GaoHaHa-IronMan** [comment]
> > 可以使用 GOARCH=amd64 xgo test -v -run 运行，将架构切换到amd64就能正常运行了，跟在ARM架构上运行gomonkey类似。
> 
> @GaoHaHa-IronMan 这个问题与xgo没有关系，你用go test也会有这个问题。
> 
> 根本原因是sonic这个包只支持amd64。
> 
> 你测试的代码有吗，为什么会引用到github.com/bytedance/sonic/internal/rt这个包呢？

使用go test没有问题，测试代码里没用sonic但是我的业务代码里使用了sonic，使用的方法也只是Unmarshal和Marshal方法而已，没有直接引入github.com/bytedance/sonic/internal/rt这个包

**Comment by xhd2015** [comment]
> > > 可以使用 GOARCH=amd64 xgo test -v -run 运行，将架构切换到amd64就能正常运行了，跟在ARM架构上运行gomonkey类似。
> > 
> > 
> > @GaoHaHa-IronMan 这个问题与xgo没有关系，你用go test也会有这个问题。
> > 根本原因是sonic这个包只支持amd64。
> > 你测试的代码有吗，为什么会引用到github.com/bytedance/sonic/internal/rt这个包呢？
> 
> 使用go test没有问题，测试代码里没用sonic但是我的业务代码里使用了sonic，使用的方法也只是Unmarshal和Marshal方法而已，没有直接引入github.com/bytedance/sonic/internal/rt这个包。Marshal和Unmarshal方法所在文件里有引入github.com/bytedance/sonic/internal/rt这个包。

@GaoHaHa-IronMan 有没有一小段代码可以贴出来看看👀， 我没有arm机器，不好构造这个用例

**Comment by GaoHaHa-IronMan** [comment]
> > > > 可以使用 GOARCH=amd64 xgo test -v -run 运行，将架构切换到amd64就能正常运行了，跟在ARM架构上运行gomonkey类似。
> > > 
> > > 
> > > @GaoHaHa-IronMan 这个问题与xgo没有关系，你用go test也会有这个问题。
> > > 根本原因是sonic这个包只支持amd64。
> > > 你测试的代码有吗，为什么会引用到github.com/bytedance/sonic/internal/rt这个包呢？
> > 
> > 
> > 使用go test没有问题，测试代码里没用sonic但是我的业务代码里使用了sonic，使用的方法也只是Unmarshal和Marshal方法而已，没有直接引入github.com/bytedance/sonic/internal/rt这个包。Marshal和Unmarshal方法所在文件里有引入github.com/bytedance/sonic/internal/rt这个包。
> 
> @GaoHaHa-IronMan 有没有一小段代码可以贴出来看看👀， 我没有arm机器，不好构造这个用例

`package main

import (
	"fmt"
	"github.com/bytedance/sonic"
	"io"
	"net/http"
	"strconv"

	"github.com/julienschmidt/httprouter"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

type User struct {
	ID   int
	Name string
}

func NewMySQLDB(host, port, user, pass, dbname string) (*gorm.DB, error) {
	dsn := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local",
		user, pass, host, port, dbname)
	return gorm.Open(mysql.Open(dsn), &gorm.Config{})
}

func NewUserHandler(store *gorm.DB) *UserHandler {
	return &UserHandler{store: store}
}

type UserHandler struct {
	store *gorm.DB
}

func (h *UserHandler) CreateUser(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	w.Header().Set("Content-Type", "application/json")

	body, err := io.ReadAll(r.Body)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		_, _ = fmt.Fprintf(w, `{"msg":"%s"}`, err.Error())
		return
	}
	defer func() { _ = r.Body.Close() }()

	u := User{}
	if err := sonic.Unmarshal(body, &u); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		_, _ = fmt.Fprintf(w, `{"msg":"%s"}`, err.Error())
		return
	}

	if err := h.store.Create(&u).Error; err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		_, _ = fmt.Fprintf(w, `{"msg":"%s"}`, err.Error())
		return
	}
	w.WriteHeader(http.StatusCreated)
}

func (h *UserHandler) GetUser(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
	id := ps[0].Value
	uid, _ := strconv.Atoi(id)

	w.Header().Set("Content-Type", "application/json")
	var u User
	if err := h.store.First(&u, uid).Error; err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		_, _ = fmt.Fprintf(w, `{"msg":"%s"}`, err.Error())
		return
	}
	_, _ = fmt.Fprintf(w, `{"id":%d,"name":"%s"}`, u.ID, u.Name)
}

func setupRouter(handler *UserHandler) *httprouter.Router {
	router := httprouter.New()
	router.POST("/users", handler.CreateUser)
	router.GET("/users/:id", handler.GetUser)
	return router
}

func main() {
	mysqlDB, _ := NewMySQLDB("localhost", "3306", "user", "password", "test")
	handler := NewUserHandler(mysqlDB)
	router := setupRouter(handler)
	_ = http.ListenAndServe(":8000", router)
}
`

**Comment by GaoHaHa-IronMan** [comment]
> > > > 可以使用 GOARCH=amd64 xgo test -v -run 运行，将架构切换到amd64就能正常运行了，跟在ARM架构上运行gomonkey类似。
> > > 
> > > 
> > > @GaoHaHa-IronMan 这个问题与xgo没有关系，你用go test也会有这个问题。
> > > 根本原因是sonic这个包只支持amd64。
> > > 你测试的代码有吗，为什么会引用到github.com/bytedance/sonic/internal/rt这个包呢？
> > 
> > 
> > 使用go test没有问题，测试代码里没用sonic但是我的业务代码里使用了sonic，使用的方法也只是Unmarshal和Marshal方法而已，没有直接引入github.com/bytedance/sonic/internal/rt这个包。Marshal和Unmarshal方法所在文件里有引入github.com/bytedance/sonic/internal/rt这个包。
> 
> @GaoHaHa-IronMan 有没有一小段代码可以贴出来看看👀， 我没有arm机器，不好构造这个用例

[main_test.txt](https://github.com/user-attachments/files/15613656/main_test.txt)
[main.txt](https://github.com/user-attachments/files/15613657/main.txt)
这两个文件改下后缀名，然后使用xgo test -v -run TestUserHandler_CreateUser就能复现了。

**Comment by xhd2015** [comment]
Thanks, 我测试一下

**Comment by xhd2015** [comment]
@GaoHaHa-IronMan 通过CI发现确实有这个问题，👍

https://github.com/xhd2015/xgo/pull/201/checks

<img width="1243" alt="image" src="https://github.com/xhd2015/xgo/assets/14964938/85b043ec-49d3-4d7f-9700-0c4b3aaf56d3">

我尽快解决一下

**Comment by xhd2015** [comment]
@GaoHaHa-IronMan 不过sonic确实不支持arm64, 用go运行的时候， 可以看到有这个warning
<img width="1221" alt="image" src="https://github.com/xhd2015/xgo/assets/14964938/3c3ca20c-cd3f-4c3f-8b73-614c91b103bb">

**Comment by xhd2015** [comment]
应该与这两个空函数声明有关：
https://github.com/bytedance/sonic/blob/c3fa2d31b8f6d07e8abd81317fc7350e40a34b46/internal/rt/gcwb.go#L104

```go
func StopProf()
func StartProf()
```

xgo可能没有正确处理函数体为空的情况。

我将会提2个issue：
- xgo： 修复空函数的情况
- sonic： 将这两个函数移动到对应的amd64专有文件中

**Comment by xhd2015** [comment]
@GaoHaHa-IronMan xgo v1.0.40修复了这个bug，感谢反馈，参见：https://github.com/xhd2015/xgo/releases/tag/v1.0.40

升级：
```sh
# update xgo
go install github.com/xhd2015/xgo/cmd/xgo@v1.0.40

# update dependency
go get github.com/xhd2015/xgo/runtime@v1.0.40
```

**Comment by GaoHaHa-IronMan** [comment]
> @GaoHaHa-IronMan xgo v1.0.40修复了这个bug，感谢反馈，参见：https://github.com/xhd2015/xgo/releases/tag/v1.0.40
> 
> 升级：
> 
> ```shell
> # update xgo
> go install github.com/xhd2015/xgo/cmd/xgo@v1.0.40
> 
> # update dependency
> go get github.com/xhd2015/xgo/runtime@v1.0.40
> ```

试了确实可以了。牛🐮
