### ISSUE TITLE
Windows Friendly Support

### ISSUE THREAD

**Issue by WAY29** [xhd2015/xgo#2]
1. add windows install powershell like install.ps1
2. build from source with windows met two errors:
    1. without "--local" options, goterror: `sum sha256: exec: "shasum": executable file not found in %PATH%`
    2. with "--local" options, got error: `GOOS=windows GOARCH=amd64:rename C:\Users\admin\AppData\Local\Temp\xgo-release3949503335\xgo C:\Users\admin\.xgo\bin\xgo: The system cannot find the path specified.`

Additionally, build from source binary with windows without ".exe" suffix

**Comment by xhd2015** [comment]
huh thanks WAY29 for your feedback.
There is a temporary fix for the `--local` case, just `mkdir C:\Users\admin\.xgo\bin` before you run
I don't have a windows PC on my hand so windows support is currently poor, I will solve this later.

**Comment by xhd2015** [comment]
Also you need to add `C:\Users\admin\.xgo\bin` to your system PATH variable to make xgo works.
You can update PATH variable following this tutorial: https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

**Comment by xhd2015** [comment]
Hi WAY29, I just updated master to solve the `--local` build-release mode, you can try it again, thanks!

**Comment by WAY29** [comment]
LGTM, how about use golang builtin library instead of `shasum`?

**Comment by xhd2015** [comment]
Good point, will do it.
However notice that `build-release` without `--local` is actually for maintainer to build binaries into `xgo-release/1.0.x`, then upload them to github.
If you just want to use it locally, `--local` is enough.
