### ISSUE TITLE
推荐用这个工具来 patch goruntime 代码

### ISSUE THREAD

**Issue by alpha-baby** [xhd2015/xgo#203]
目前 xgo 里面来 patch go runtime 代码挺原始的：
https://github.com/xhd2015/xgo/blob/ae8695c56e8c7f1976d409c7fba953041983c299/cmd/xgo/patch_runtime.go#L132

推荐用这个工具来做 patch
https://github.com/uber-go/gopatch

**Comment by xhd2015** [comment]
看起来挺有意思，我们之前有讨论过希望提升这个patch的格式：https://github.com/xhd2015/xgo/issues/147
有空我看一下是否值得迁移，谢谢。

**Comment by xhd2015** [comment]
uber-go patch的功能很丰富，但对于xgo来说，会引入额外的依赖，很多功能也用不到。

因此，在支持go1.23的PR中，实现了一个基础的patch:

![image](https://github.com/user-attachments/assets/80daf77b-162d-408d-bdcf-92a27bf38da7)


可以参考：
https://github.com/xhd2015/xgo/issues/169#issuecomment-2241407305

https://github.com/xhd2015/xgo/tree/master/support/transform/patch
