### ISSUE TITLE
能集成到 go test 命令吗

### ISSUE THREAD

**Issue by 12345dotblue** [xhd2015/xgo#206]
或者 xgo 是完全可以跑 历史的 go test执行的用例吗？

**Comment by xhd2015** [comment]
有两种方案使用xgo进行测试：
- xgo test， 它完全兼容go test
- 可以执行`xgo e`来打开一个UI接口，通过点击Test来执行xgo test， 参见https://github.com/xhd2015/xgo/issues/205#issuecomment-2169201846
