### ISSUE TITLE
在 Mock 结构体的方法时是否支持调用接口体其他方法

### ISSUE THREAD

**Issue by Charlie17Li** [xhd2015/xgo#268]
## 现状

如下 Demo 是在 mock SetName方法，然而 mock 方法的入参仅有 name，而没有 s * Student，这就导致无法在 mock 方法中调用接口体的其他方法。
https://github.com/xhd2015/xgo/blob/1d8b33c2ca5fafec9439a1ec7adcdc591db705b9/doc/demo/demo_test.go#L66-L68

## 期望

```
 mock.Patch(student.SetName, func(s * Student, name string) { 
        old := s.GetName()
        s.name = old + " subfix"
 	return 
 }) 
```

**Comment by xhd2015** [comment]
# 为什么Patch替代函数没有receiver?
`mock.Patch(fn, replacer)`的参数要求是，`fn`和`replacer`的签名要完全一致。

当引用`student.SetName`时，实际上这个值的类型就是 `func(name string)`, 验证:
```go
package main

import "fmt"

type Student struct {
}

func (s *Student) SetName(name string) {
}

func main() {
	s := &Student{}
	fmt.Printf("s.SetName: %T\n", s.SetName)
	fmt.Printf("(*Student).SetName: %T\n", (*Student).SetName)
}
```
输出:
```
s.SetName: func(string)
(*Student).SetName: func(*main.Student, string)
```

(https://go.dev/play/p/4nFaM0LLgAy)

# Workaround
尽管`s.SetName`无法引用receiver，但是通过`(*Student).SetName`可以达成相同的目的, 只不过稍微复杂一点:
```go
someStudent := &Student{}
mock.Patch( (*Student).SetName, func(s * Student, name string) { 
        if s != someStudent {
                return
        }
        old := s.GetName()
        s.name = old + " subfix"
 	return 
}) 
```

**Comment by Charlie17Li** [comment]
明白了，感谢！
