### ISSUE TITLE
Running Test did not end and was blocked.

### ISSUE THREAD

**Issue by Zzhiter** [xhd2015/xgo#94]
Error reported at the beginning：“failed to auto import github.com/xhd2015/xgo/runtime/trace”
`
➜  json git:(235ef28b) ✗ xgo test -v -run TestDecoder --strace ./decode_test.go

go: -mod may only be set to readonly when in workspace mode, but it is set to "mod"
        Remove the -mod flag to use the default readonly value,
        or set GOWORK=off to disable workspace mode.
WARNING: --strace requires: import _ "github.com/xhd2015/xgo/runtime/trace"
   failed to auto import github.com/xhd2015/xgo/runtime/trace: exit status 1
=== RUN   TestDecoder
=== RUN   TestDecoder/#00
=== RUN   TestDecoder/#01
=== RUN   TestDecoder/#02
--- PASS: TestDecoder (0.02s)
    --- PASS: TestDecoder/#00 (0.00s)
    --- PASS: TestDecoder/#01 (0.00s)
    --- PASS: TestDecoder/#02 (0.00s)
PASS
ok      command-line-arguments  0.022s
`
Then I saw this issue: https://github.com/xhd2015/xgo/issues/87
but I use the go.work.
Then I import the module:
![image](https://github.com/xhd2015/xgo/assets/61727602/eced7464-0178-4703-8f61-38c3f6b1e26a)
But this time the test is blocked.
![image](https://github.com/xhd2015/xgo/assets/61727602/e6539bb1-b176-4e56-973a-e2248a94c530)

My version is:
![image](https://github.com/xhd2015/xgo/assets/61727602/6c98fb66-a33c-4f99-88f3-0750737da583)

**Comment by xhd2015** [comment]
Thanks for reporting this issue. Few questions:
- May I know which repository you are working one?(knowing the project structure helps)
- Which go version?
- After you manually add `import _ "github.com/xhd2015/xgo/runtime/trace"`, have run `go mod tidy`?
- Can you run with normal go(i.e. without xgo) to see if the tests still block?

**Comment by Zzhiter** [comment]
1. https://github.com/protocolbuffers/protobuf-go  and the commit version is 235ef28b
![image](https://github.com/xhd2015/xgo/assets/61727602/32c7ed26-2e0a-4a6a-8b07-9de9a9f92ce7)
Test file is protobuf-go/internal/encoding/json/decode_test.go
2. go version is 1.21.9
![image](https://github.com/xhd2015/xgo/assets/61727602/d3f3bcaa-7ea3-4f82-a104-00e09729c35a)
3. Yes, I have run it
4. Normal go test will not block
![image](https://github.com/xhd2015/xgo/assets/61727602/39c74575-d6be-44da-a5f3-7037a2d76161)

**Comment by xhd2015** [comment]
Thanks, will investigate as soon as possible

**Comment by xhd2015** [comment]
@Zzhiter Just investigated, and it seems with `--strace` xgo will block when there are many tests to run.

I suggest adding `--strace` to only individual case, for example:
```sh
xgo test -run 'TestDecoder/#08' --strace ./internal/encoding/json
```

This will generate corresponding trace, and will not block.

**Comment by Zzhiter** [comment]
Wow, thanks for your help
