### ISSUE TITLE
Proposal: xgo tool coverage merge -o cov.out cov-a.out cov-b.out

### ISSUE THREAD

**Issue by xhd2015** [xhd2015/xgo#98]
Add a tool to merge coverage profiles of multiple running into one profile.
Write output to stdout if `-o` is missing.

**Comment by ccoVeille** [comment]
This tool could be moved to his own repository, or could be documented as a binary that anyone could reuse no ?

**Comment by xhd2015** [comment]
@ccoVeille Yes it could be used as a standalone binary:
```sh
go install github.com/xhd2015/cmd/coverage@latest
coverage <cmd> [args]
```

Xgo packs it for convenience:
```sh
xgo tool coverage <cmd> [args]
```

**Comment by ccoVeille** [comment]
> @ccoVeille Yes it could be used as a standalone binary:
> ```sh
> go install github.com/xhd2015/cmd/coverage@latest
> coverage <cmd> [args]
> ```
> 
> Xgo packs it for convenience:
> ```sh
> xgo tool coverage <cmd> [args]
> ```

coverage seems a bad name for a standalone binary

**Comment by xhd2015** [comment]
> > @ccoVeille Yes it could be used as a standalone binary:
> > ```shell
> > go install github.com/xhd2015/cmd/coverage@latest
> > coverage <cmd> [args]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Xgo packs it for convenience:
> > ```shell
> > xgo tool coverage <cmd> [args]
> > ```
> 
> coverage seems a bad name for a standalone binary

Or could be renamed to these candidates:
- `coverutil`
- `covutil`
- `covtool`
- `xgocov`
- `coverage-tool`
- `cover-tool`
- `cover-util`
- `xgo-coverage-tool`
- `xgo-cover-tool`

Which do you think makes more sense?

**Comment by ccoVeille** [comment]
I would say
- coverage-tool
- go-coverage-tool

I would tend to choose the second one, as it's go related.

My point of view about other suggestions
- util is not specific
- xgo shouldn't be used in the name as it's not dependent to xgo
- cover is for books, or comforter 😅

**Comment by xhd2015** [comment]
OK,  seems fine, I'll rename the standalone tool name to `go-coverage-tool` later.
